- gh-pages/component/Demo/codemirror.css
Just a minor styling change to make it easier to read the line numbers when scrolling past code horizontally.
> feat: added backdrop-filter blur for codemirror gutters

- packages/plugin-listener/README.md
The `@milkdown/plugin-history` import should be `@milkdown/plugin-listener`.
> fix: plugin-listener import example

- integration-test/tests/editor.spec.ts
- packages/preset-commonmark/src/node/image.ts
Current InputRule for image node uses the left double quotation mark (“, U+201C). 
Isn't this a typo for the normal quotation mark (", U+0022)?
CommonMark image requires a white space and a normal quotation mark before title strings.
https://spec.commonmark.org/0.30/#example-571
I have tried to make the regular expression closer to the Common Mark specification.
> fix: regexp for image with title

- packages/design-system/src/default-value.ts
- packages/design-system/src/types.ts
- packages/plugin-menu/src/button.ts
- packages/plugin-menu/src/divider.ts
- packages/plugin-menu/src/manager.ts
- packages/plugin-menu/src/select.ts
- packages/theme-nord/src/slots.ts
- Use HTML button elements rather than divs to improve semantics and accessibility
- Add classes to buttons and dividers to improve the ability to customise the styling of those elements outside of the theme
- Add a human-readable label for slots which is used as title and aria-label on the menu buttons
✅ Closes: [218](https://github.com/Saul-Mirone/milkdown/issues/218)
> feat: 🎸 use button elements within menu, w classes and labels

- packages/exception/package.json
For those project using yarn, yarn install will yield warning for
peerDependency @milkdown/core. Add an option to elimiate it.
> chore: 🤖 Add 'peerDependenciesMeta' to package.json

- package.json
- packages/plugin-emoji/src/filter/helper.ts
Hello! I've been loving milkdown. 
To get a little further into the code, I thought it'd be a useful pedagogical exercise for me to send the world's smallest diff to support emoji typeahead syntax with uppercase inputs. 
While writing docs with milkdown, I've often wanted to add emoji to headers. Since headers are often written in titlecase, I've found myself typing emoji with uppercase letters (:HI ... ). I think the emoji typeahead should match these strings. Just now while typing this message, I notice that Github.com's markdown parser handles uppercase emojis :) 
After I made my commit, I went to run the tests and got the following stacktrace:
```
> eslint **/{src,gh-pages,examples}/**/*.{js,ts,tsx}
Oops! Something went wrong! :(
ESLint: 8.7.0
No files matching the pattern …
```
> Downcase emoji searches

- packages/plugin-tooltip/src/input-manager/index.ts
- packages/plugin-tooltip/src/utility/input.ts
This MR seeks to expedite the process of setting link and image source values through the tooltip input.
In the current demo, one needs to click four times to create a link:
1) Click a link button (in the menu or tooltip) to add a mark to some text
2) Click the text that now has a link mark
3) Click the input so that one can start typing the link href
4) Click the submit button to persist the link text and close the modal
This MR reduces the number of clicks required to two:
1) Click a link button (in the menu or tooltip) to add a mark to some text
2) Click the text that now has a link mark
I'd like to make that second click unnecessary as well, but thought I'd send these changes in and make sure this looks alright before moving to that next step...
Any thoughts or feedback is welcome! …
> feat: autofocus tooltip input & submit on Enter key

- packages/plugin-clipboard/src/clipboard.ts
I was switching to use Milkdown in one of my projects when I discovered that the `ViewOptions` I intended to pass to `ProseMirror` were not being respected.
E.g., I was passing in a `dispatchTransaction` prop:
```
ctx.set(
editorViewOptionsCtx,
{
editable: () => !readOnly,
dispatchTransaction(tr) {...}
},
);
```
but it was never making it to the editor.
Putting a `console.log` in `core/internal-plugin/editor-view.ts` confirmed that the prop was missing.
The culprit was the clipboard plugin -- it updates the view options without preserving the existing options.
---
**Note:** I think a better approach might be to change the `Ctx` API to add a `ctx.merge` method. Merge would merge the new state with the old state. This will prevent plugin authors from making this same mistake again.
lmk what …
> Stop clobbering view options in the clipboard plugin

- gh-pages/component/MilkdownEditor/editor.ts
Noted that I haven't sync gh-page with latest mermaid API change, I made a commit to fix this.
I tried to use git rebase to clean up my fork, but used git push -f. I don't know whether if I'm doing right. Please review it, and sorry for bothering you once again. 🙏
> fix: 🐛 diagram is not loaded in doc.

- packages/ctx/src/timing/timing.ts
For multiple editor, event will dispatch to all listeners, which remove other editors' listener.
Run an example.
> fix: 🐛 multiple editor timing event dispatch

- packages/preset-commonmark/src/node/bullet-list.ts
- packages/preset-commonmark/src/node/heading.ts
- packages/preset-commonmark/src/node/list-item.ts
- packages/preset-commonmark/src/node/ordered-list.ts
列表编辑之后列表项之间会多出来一行。
```
1. 1
2. 2
```
会变成
```
1. 1
2. 2
```
remark 的 ast 有一个 `spread` 属性，经过 milkdown 转换后丢失了，所以存储一下 `spread` 属性，生成 ast 时带上 `spread` 属性，就不会多出来一行。如果原来 markdown 文档的列表有空行，转换后也可以保持原状。
> feat: 🎸 list and listItem support attr spread

- packages/plugin-diagram/src/index.ts
> fix: 🐛 export diagramNode for config

- packages/preset-commonmark/src/mark/link.ts
Chinese quotation mark.
https://regexr.com/
> fix: 🐛 link title parsing regex

- e2e/cypress/e2e/preset-commonmark/input.cy.ts
- e2e/snapshots.js
- packages/plugin-block/src/block-menu-dom.ts
- packages/plugin-block/src/block-service.ts
- packages/preset-commonmark/src/mark/em.ts
- packages/preset-commonmark/src/mark/strong.ts
有时在空行前触发块级菜单，鼠标按下后slash插件会重新渲染p标签，鼠标抬起后#target已脱离文档，所以改为鼠标按下时缓存#targetDOMRect
> fix: 🐛 plugin-block menu position wrong

- e2e/cypress/e2e/preset-commonmark/input.cy.ts
- e2e/cypress/e2e/preset-commonmark/shortcut.cy.ts
- e2e/cypress/e2e/preset-gfm/shortcut.cy.ts
- e2e/snapshots.js
- package.json
- packages/plugin-math/src/math-inline/index.ts
- packages/plugin-tooltip/src/item.ts
- packages/preset-commonmark/src/mark/code-inline.ts
- packages/preset-commonmark/src/mark/em.ts
- packages/preset-commonmark/src/mark/link.ts
- packages/preset-commonmark/src/mark/strong.ts
- packages/preset-commonmark/src/node/heading.ts
- packages/preset-commonmark/src/node/paragraph.ts
- packages/preset-commonmark/src/plugin/index.ts
- packages/preset-commonmark/src/plugin/inline-sync.ts
- packages/preset-gfm/src/strike-through.ts
- packages/transformer/src/parser/index.ts
- packages/transformer/src/parser/state.ts
- packages/utils/src/index.ts
- tsconfig.base.json
There're lots of bugs caused by consistency between markdown AST and UI.
For example:
https://github.com/Saul-Mirone/milkdown/issues/637
https://github.com/Saul-Mirone/milkdown/issues/553
https://github.com/Saul-Mirone/milkdown/issues/622
The `inline-sync-plugin` can help to solve this issue. Instead of using inputrules to check user input, this plugin keep sync the prosemirror node between markdown AST for inline nodes (such as `paragraph` and `heading`).
Manually test and e2e test.
> Inline sync plugin

- packages/preset-commonmark/src/plugin/inline-sync/index.ts
1. If active inline sync plugin at readonly, it causes heading flash after clicked.
2. If no debounce, it cause infinite loop of inline sync update. (by performance tool)
Both of above cause by inputing content like
```md
1. a
```
I think multiple plugins break each other.
But i am not sure whether debounce will cause state lost or not, please check it.
Run an example.
> fix: 🐛 inline sync plugin debounce and disable at readonly

- packages/core/src/editor/editor.ts
- packages/core/src/internal-plugin/commands.ts
- packages/core/src/internal-plugin/config.ts
- packages/core/src/internal-plugin/editor-state.ts
- packages/core/src/internal-plugin/editor-view.ts
- packages/core/src/internal-plugin/init.ts
- packages/core/src/internal-plugin/parser.ts
- packages/core/src/internal-plugin/schema.ts
- packages/core/src/internal-plugin/serializer.ts
- packages/core/src/internal-plugin/theme.ts
- packages/ctx/src/context/container.spec.ts
- packages/ctx/src/context/container.ts
- packages/ctx/src/context/slice.ts
- packages/ctx/src/plugin/ctx.ts
- packages/ctx/src/plugin/env.ts
- packages/ctx/src/plugin/index.ts
- packages/ctx/src/plugin/post.ts
- packages/ctx/src/plugin/types.ts
- packages/ctx/src/timing/clock.spec.ts
- packages/ctx/src/timing/clock.ts
- packages/ctx/src/timing/timing.ts
This feature is designed to make plugins can be removed.
Closes: https://github.com/Saul-Mirone/milkdown/issues/442
```typescript
import { myPlugin } from 'my-plugin';
let editor;
// after created
editor = await Editor.make()
.use(myPlugin)
.create();
await editor.remove(myPlugin)
// before created
editor = await Editor.make()
.use(myPlugin)
.remove(myPlugin);
```
Plugin now can do cleanup it's state in a new `post` progress.
```typescript
const plugin: MilkdownPlugin = (pre) => {
// pre progress
return (ctx) => {
// run progress
return (post) => {
// post progress
}
}
}
```
The post progress will execute when editor trying to remove the plugin.
Since we have a `remove` method for editor, it'll also …
> [RFC]: make plugins can be removed

- packages/plugin-emoji/src/filter/index.ts
- packages/plugin-tooltip/src/button-manager/calc-button-pos.ts
- packages/preset-commonmark/src/mark/link.ts
- packages/preset-gfm/src/table/operator-plugin/calc-pos.ts
- packages/theme-pack-helper/src/renderer-preset/input-chip.ts
✅ Closes: #795
Adjust the tooltip display position when tooltip is displayed near the top or right side of the editor.
1. Test cases:
> fix: 🐛 tooltip display overflow

- packages/plugin-emoji/src/filter/index.ts
- packages/plugin-tooltip/src/button-manager/calc-button-pos.ts
- packages/preset-commonmark/src/mark/link.ts
- packages/preset-gfm/src/table/operator-plugin/calc-pos.ts
- packages/theme-pack-helper/src/renderer-preset/input-chip.ts
I'm sorry for some problems created in #801.
**Bugs:**
1. Emoji Filter left position does not calculate the scrollbar inside the Filter, causing the editor to have a scrollbar.
2. The top position of Filter is wrong when entering emoji in multi-line text.
https://milkdown-git-fork-ihapboy-feat-optimize-emoj-8d4d31-saul-mirone.vercel.app/online-demo?text=EYYwJgBAhqY%2B1aPPSrlye12u1wjnofnhAFwDOAtgFC3GYnNNqMFsqMYc%2FdEsIARwDuAUz6CBnGb2kZJMxQvkEIw8co5zSU3UtXt%2BWSnDSmAllFEB7CVEoQjeri9Yr9H1wc%2Fbuo%2B19nH28vdz83HVC1AK1gsKjw%2BNwKR2j%2BUyhzMCtbe0dkwpZEkuN04v9NQwrIsqSakPrZMo1A8ubazsbSt2hM7NyROz76UbHxsaA%3D%3D%3D
1. Test cases:
- …
> fix: 🐛 emoji-filter-position

- packages/preset-commonmark/src/mark/link.ts
- website/pages/official-plugins/preset-commonmark/index.md
✅ Closes: #808
1. display input chip when selected for link text
2. add an option `displayWhenSelected` to `link` node (default: `false`)
1. Test cases:
```typescript
.use(
gfm.configure(link, {
input: {
displayWhenSelected: true,
},
}),
)
```
> feat: 🎸 add an option to show input chip when selected for link

- packages/plugin-emoji/src/filter/helper.ts
- packages/plugin-emoji/src/filter/index.ts
**Bug:** mouse enter/leave can't update active item.
**Fixed:**
> fix: 🐛 emoji filter update active item by mouse event

- packages/plugin-slash/src/config.ts
**Bug:** Slash placeholder is also displayed when `editable` is `false`
**Fixed:**
> fix: 🐛 hide slash placeholder when editable is false

- packages/preset-gfm/src/table/operator-plugin/index.ts
- packages/preset-gfm/src/table/plugin/column-resizing.ts
**Bug:** Table operator and column resizing handle is also displayed when `editable` is `false`
**Fixed:**
> fix: 🐛 disable table operator when editable is false

- packages/ctx/src/plugin/ctx.spec.ts
- packages/ctx/src/plugin/ctx.ts
✅ Closes: #906
Fix the issue that ctx won't accept string as slice type.
Unit Test
> fix: 🐛 string slice type for ctx

- .github/workflows/ci-for-pr.yml
- packages/prose/package.json
- packages/prose/rollup.config.js
- packages/theme-nord/package.json
- packages/theme-nord/src/index.ts
- pnpm-lock.yaml
✅ Closes: #911
Expose styles for:
- `prosemirror-view/style/prosemirror.css` -> `@milkdown/prose/view/style/prosemirror.css`
- `prosemirror-tables/style/tables.css` -> `@milkdown/prose/tables/style/tables.css`
Tested manually.
> fix: 🐛 expose styles from prosemirror packages

- package.json
node v16 won't work since it will throw error when build packages unless add a `--experimental-json-modules` flag:
```
[!] TypeError: Unknown file extension ".json"
```
This problem may waste time of community developers.
> chore: update engines requirement

- packages/preset-commonmark/src/node/hardbreak.ts
Add leafText for `hardbreak` node, to make `nodeContainingHardbreak.textContent` work correctly.
Pass all tests
> fix: add hardbreak leafText

- packages/core/src/internal-plugin/commands.ts
- packages/core/src/internal-plugin/editor-state.ts
- packages/core/src/internal-plugin/editor-view.ts
- packages/core/src/internal-plugin/init.ts
- packages/core/src/internal-plugin/parser.ts
- packages/core/src/internal-plugin/schema.ts
- packages/core/src/internal-plugin/serializer.ts
✅ Closes: #974
Fix multiple editor instances will share instances.
E2E
> fix: 🐛 support for multiple editor instances

- e2e/cypress/e2e/preset-gfm/input.cy.ts
- packages/preset-commonmark/src/composed/commands.ts
- packages/preset-commonmark/src/node/list-item.ts
✅ Closes: #997
Bind the new `liftFirstListItem` command to `Backspace` and `Delete` to avoid list items cannot be deleted in some cases.
E2E
> feat: 🎸 add a command to lift first list item

- packages/plugin-slash/src/slash-provider.ts
This pull request expose trigger of plugin-slash for show content not only by the '/' key. It's possible to override `shouldShow` to do this approach, but you'd end up having to rewrite other functions like `getContent()`, and this change doesn't bring any breaking changes.
I implemented the same idea in a project by wrapping this plugin and it worked properly:
> feat(plugin-slash): expose trigger key

- packages/preset-commonmark/src/node/heading.ts
The keys of the heading shortcuts are not set correctly.
Automated tests.
> fix: set keys of heading shortcuts correctly

- e2e/cypress/e2e/plugin-clipboard/plugin.cy.ts
- packages/plugin-clipboard/src/index.ts
Closes: https://github.com/Milkdown/milkdown/issues/1023
E2E
> fix: marks won't be extended when pasting pure text

- packages/theme-nord/package.json
✅ Closes: #1075
Fix the issue that import theme-nord will throw error in typescript.
Manully
> fix: 🐛 missing type error in theme-nord

- packages/theme-nord/src/style.css
`th` tag was out of `.milkdown-theme-nord.prose` scope, generating unwanted side effects.
`pnpm test` run passed
> fix: 🐛 theme-nord th tag fix

- package.json
- pnpm-lock.yaml
Deduplicate npm packages.
Use [nolyfill](https://github.com/SukkaW/nolyfill) to speed up install.
`node_modules 762MB -> 661MB`
E2E
> chore: dedupe packs

- e2e/cypress/e2e/preset-commonmark/input.cy.ts
- packages/core/src/internal-plugin/editor-state.ts
Undo inputrule when press `Backspace`.
E2E
> feat: undo inputrule when backspace

- packages/plugin-emoji/package.json
- packages/plugin-emoji/src/__internal__/parse.ts
- packages/plugin-emoji/src/__internal__/remark-twemoji.ts
- pnpm-lock.yaml
✅ Closes: #1177
Fix missing `TwemojiOptions` type in emoji plugin.
CI
> fix: 🐛 missing twemoji type

- packages/core/package.json
- packages/ctx/package.json
- packages/exception/package.json
- packages/plugin-automd/package.json
- packages/plugin-block/package.json
- packages/plugin-clipboard/package.json
- packages/plugin-collab/package.json
- packages/plugin-cursor/package.json
- packages/plugin-diagram/package.json
- packages/plugin-emoji/package.json
- packages/plugin-history/package.json
- packages/plugin-indent/package.json
- packages/plugin-listener/package.json
- packages/plugin-math/package.json
- packages/plugin-prism/package.json
- packages/plugin-slash/package.json
- packages/plugin-tooltip/package.json
- packages/plugin-trailing/package.json
- packages/plugin-upload/package.json
- packages/preset-commonmark/package.json
- packages/preset-commonmark/src/index.ts
- packages/preset-gfm/package.json
- packages/react/package.json
- packages/transformer/package.json
- packages/utils/package.json
- packages/vue/package.json
Add exports fields in all plugins' `package.json`.
CI
> chore: 🤖 add exports in package json

- packages/components/src/link-tooltip/edit/edit-view.ts
- packages/components/src/link-tooltip/preview/preview-view.ts
- packages/crepe/src/feature/block-edit/handle/index.ts
- packages/crepe/src/feature/block-edit/menu/index.ts
- packages/crepe/src/feature/toolbar/index.ts
Add `appendTo` property for tippy options to silent the warning.
CI
> fix: 🐛 silent tippy warnings

- e2e/package.json
- e2e/src/plugin-emoji/main.stories.ts
- e2e/src/preset-commonmark/commands.stories.ts
- e2e/src/style.css
- packages/plugin-emoji/src/__internal__/remark-twemoji.ts
- pnpm-lock.yaml
> fix: 🐛 should not throw error when emoji in code

- packages/plugin-block/src/block-service.ts
The lodash.debounce function creates a wrapped function, and if you recreate the wrapped function each time, debounce will not take effect.
The following sample code briefly explains how it works, you can see that the timerId is saved in the context of the debounce function, you need to save it to achieve the debounce effect, if you call the lodash.debounce function every time, it will always be the initial value.
```javascript
function debounce(fn, wait = 500) {
let timerId;
return (...args) => {
clearTimeout(timerId);
timerId = setTimeout(() => {
fn(...args);
}, wait);
};
}
```
**before**
> You can see that the buttons on the left side of the mouse are constantly jumping when you move the mouse, and …
> fix(plugin-block): fix mouse move debouncing does not work

- packages/components/src/code-block/view/component.ts
- packages/components/src/code-block/view/node-view.ts
✅ Closes: #1293
Fix empty language for code block component.
CI
> fix: 🐛 code block component can't work for empty language

- packages/preset-commonmark/src/plugin/sync-heading-id-plugin.ts
✅ Closes: #1252
Heading id not synced in readonly mode.
CI
> fix: 🐛 heading id in readonly mode

- packages/preset-commonmark/src/node/list-item.ts
✅ Closes: #1276
Allow list item to have other types of block as first child.
CI
> fix: 🐛 list item can have other block as first children

- packages/preset-commonmark/src/node/list-item.ts
✅ Closes: #1270
The `liftListItem` command has wrong command key.
CI
> fix: 🐛 liftListItem command has wrong command key

- e2e/src/crepe/main.ts
- packages/components/src/link-tooltip/preview/preview-view.ts
Destorying crepe will throw an error.
CI
> fix: 🐛 crepe destroy throw an error

- packages/components/src/__internal__/helper.ts
- packages/components/src/code-block/view/component.ts
- packages/components/src/code-block/view/index.ts
- packages/components/src/code-block/view/node-view.ts
- packages/components/src/image-block/view/component.ts
- packages/components/src/image-block/view/index.ts
- packages/components/src/image-inline/view.ts
- packages/components/src/link-tooltip/edit/edit-configure.ts
- packages/components/src/link-tooltip/preview/preview-configure.ts
- packages/components/src/list-item-block/view.ts
- packages/crepe/src/feature/block-edit/handle/index.ts
- packages/crepe/src/feature/block-edit/menu/index.ts
- packages/crepe/src/feature/toolbar/index.ts
- packages/crepe/src/utils/index.ts
Add readonly support for image block and code block.
CI
> feat: add better readonly support for crepe

- e2e/src/components/image-block.css
Image block style offset in storybook
CI
> fix: image block style offset in storybook

- packages/crepe/src/feature/block-edit/handle/index.ts
- packages/crepe/src/feature/block-edit/style.css
- packages/plugin-block/package.json
- packages/plugin-block/src/block-provider.ts
- packages/plugin-emoji/package.json
- pnpm-lock.yaml
Replace tippy with floating ui in plugin block
> feat: replace tippy with floating ui in plugin block

- e2e/stories/components/link-tooltip.css
- packages/components/package.json
- packages/components/src/link-tooltip/edit/edit-component.ts
- packages/components/src/link-tooltip/edit/edit-view.ts
- packages/components/src/link-tooltip/preview/preview-configure.ts
- packages/components/src/link-tooltip/preview/preview-view.ts
- packages/crepe/src/feature/block-edit/handle/index.ts
- packages/crepe/src/feature/toolbar/index.ts
- packages/crepe/src/theme/classic-dark/style.css
- packages/crepe/src/theme/classic/style.css
- packages/crepe/src/theme/common/link-tooltip.css
- packages/crepe/src/theme/common/toolbar.css
- packages/plugins/plugin-block/src/block-provider.ts
- packages/plugins/plugin-tooltip/package.json
- packages/plugins/plugin-tooltip/src/tooltip-provider.ts
- packages/plugins/preset-gfm/src/composed/plugins.ts
- pnpm-lock.yaml
Migrate the tippy package to floating ui in plugin-tooltip
CI and manully
> feat: migrate to floating ui in plugin tooltip

- packages/crepe/src/feature/block-edit/menu/index.ts
- packages/crepe/src/theme/common/block-edit.css
- packages/plugins/plugin-slash/package.json
- packages/plugins/plugin-slash/src/slash-provider.ts
- pnpm-lock.yaml
Migrate tippy in slash plugin to `@flating-ui/dom`
CI & Manually
> feat: migrate tippy to floating ui in plugin slash

- e2e/cypress/e2e/preset-commonmark/shortcut.cy.ts
- packages/transformer/src/serializer/state.ts
✅ Closes: 1402
Auto move spaces for marks.
Test cases.
> fix: 🐛 marks end with space with lead to wrong markdown

- packages/crepe/rollup.config.js
Crepe bundle should treat milkdown as external
Manually
> fix: crepe bundle contains milkdown kit

- packages/plugins/plugin-tooltip/src/tooltip-provider.ts
Should not auto focus the editor on loaded.
Manually.
> fix: tooltip plugin will make the editor auto focused

- .github/workflows/ci.yml
When `oxlint` gets run in CI, lint warnings will be printed with a format that allows Github to display them as annotations on your PR. Thanks for using Oxlint <3
N/A
> ci: print lint warnings with github-compatible format

- .changeset/wet-dolphins-sniff.md
- packages/crepe/package.json
- packages/crepe/src/feature/code-mirror/index.ts
- pnpm-lock.yaml
The previous default theme has an unacceptable dependency `@babel/runtime`
> fix: crepe codemirror wrong dependency

- packages/crepe/src/feature/toolbar/component.ts
- using the crepe bundle inside a form triggers a submit when a button in the toolbar is pressed
- the default type of a button is `submit`, changing it to type `button` prevents this
- there are potentially more cases of a missing button type, but didn't wanna explode the scope of this pr
- checked on storybook that crepe stories are rendering and also that `type="button"` is present
> fix(crepe): button type in toolbar

- packages/components/src/code-block/view/component.ts
- packages/components/src/table-block/view/component.ts
- fixed buttons in used in table and code-block by adding `type="button"`
- fixes #1531 1531
- tested in storybook
> fix(crepe): submits buttons in table and code block

- packages/crepe/src/feature/block-edit/menu/component.ts
Addressing issue reported in #1536
Before: hover index was out of menu
https://github.com/user-attachments/assets/a3e21563-5749-4444-8476-50dc5e4abaf8
After: hover index reset to zero when out of bounds
https://github.com/user-attachments/assets/805f312a-5a96-4416-b480-f40bf103fcd5
> fix(slash): reset index when out of bounds

- packages/prose/src/toolkit/input-rules/custom-input-rules.ts
Specifying `undoable` for inputrules does not currently seem to work. 
The upstream implementation of `run` from prosemirror-inputrules checks if the [rule is undoable](https://github.com/ProseMirror/prosemirror-inputrules/blob/8433778a3ce4e45c0188341b72fd71da3a440b5b/src/inputrules.ts#L107) before adding the meta information. The custom implementation of the `run` function in Milkdown does not seem to do that [here](https://github.com/Milkdown/milkdown/blob/a1262cfa933f04a1be8cc976957c12c0ba2e346c/packages/prose/src/toolkit/input-rules/custom-input-rules.ts#L25).
Not all the type information seems to be captured for the `InputRule` class, such as the [`undoable` …
> fix(prosemirror): undoable inputrules

- packages/crepe/src/theme/common/link-tooltip.css
- storybook/stories/components/link-tooltip.css
Go to https://milkdown.dev/docs/api/plugin-diagram 
Hover the link. It shows "https://mermaid-". The full link is https://mermaid-js.github.io/mermaid/#/. It looks like the intent of the CSS is to apply an ellipsis but that doesn't happen because the text wraps.
`pnpm build` `pnpm start`, compared in storybook
Before:
After:
> fix: link preview text not properly truncated

- e2e/package.json
- e2e/src/crepe/index.html
- e2e/src/crepe/index.ts
- e2e/src/crepe/main.ts
- e2e/src/data.ts
- e2e/tests/crepe/latex.spec.ts
- packages/crepe/src/feature/latex/block-latex.ts
- packages/crepe/src/feature/latex/index.ts
- pnpm-lock.yaml
> test: add e2e for latex feature

- .changeset/modern-buckets-tease.md
- package.json
- scripts/changelog.mjs
> chore: changeset release

- packages/components/src/list-item-block/view.ts
> ✅ Closes: #1524
In Angular, the change detection mechanism listens for changes in the data and updates the view immediately. When you use Promise.resolve().then(...), the callback function is placed in a microtask queue and executed at the end of the current JavaScript event loop. Since Angular's change detection mechanism executes synchronously in the current event loop, view.dispatch triggers the view update immediately, causing the selection settings to take effect immediately.
setTimeout puts the callback function into the macro queue and waits for the next event loop before executing it. This means that view.dispatch will be executed after Angular's current change detection cycle, avoiding conflicts with Angular's change detection mechanism.
In some cases, Angular's change …
> fix: 🐛 incompatibility between Promise.resolve and angular change detection mechanism

- .github/workflows/ci.yml
- packages/crepe/src/core/crepe.ts
- packages/crepe/src/core/index.ts
- packages/crepe/src/core/slice.ts
- packages/crepe/src/index.ts
Add crepe ctx to make users can access crepe from editor
CI
> feat: add crepe ctx to make users can access crepe from editor

- packages/integrations/react/package.json
- packages/integrations/react/src/types.ts
- packages/integrations/vue/package.json
- packages/integrations/vue/src/types.ts
- pnpm-lock.yaml
Make react and vue `useEditor` hook accept crepe editor.
> feat: make integrations accept crepe editor

- packages/components/package.json
- packages/components/src/image-block/view/component.ts
- packages/components/src/image-inline/component.ts
- pnpm-lock.yaml
The current packages for inline and image blocks use crypto.randomuuid to generate UUID for useState but crypto.randomuuid is not available in non-HTTPS context. This means it cannot run in insecure context.
I ran the tests and it passed all tests (pnpm test). I also used the mono repo in my existing project and it solves the issue.
I ran the package in an insecure context and I no longer run into issues. I fixed the issue by including nanoid to generate random UUIDs instead of relying on crypto. It adds bloat but nanoid is reliable and is one of the smallest (if not the smallest) package.
> fix: allow running in insecure context

- packages/integrations/react/src/use-get-editor.ts
- packages/integrations/vue/src/use-get-editor.ts
Fix destroy when using crepe with react/vue.
CI
> fix: react and vue destroy when using crepe

- packages/components/src/image-block/view/component.ts
- packages/components/src/image-block/view/event.ts
Should disable image resizer for readonly mode.
Manually
> fix: should disable image resizer for readonly mode

- packages/crepe/src/feature/block-edit/menu/config.ts
Fixes #1760 - also updated to properly allow disabling of Table in Advanced Block Edit menu.
I ran the pnpm test script which has passed, and I have tested using a pnpm pack command to integrate the change into my project that discovered the problem. This fixes the issue, if the configuration is set to now show image uploads or tables they are not present in the menu. If the configuration does not specify, then they will appear as before.
This is my first ever PR so please be gentle ;-)
———————————————————————————————————————————————————————————————————————————————
NX   Successfully ran target tsc for 29 projects and 29 tasks they depend on (40s)
View logs and investigate cache misses at https://nx.app/runs/dFNlOkCTqJ
> @milkdown/monorepo@0.0.0 test:unit …
> Check for isImageBlockEnabled and isTableEnabled

- packages/crepe/src/feature/block-edit/menu/index.ts
Should not display slash menu if selection is not at the end of the line.
Manually.
> fix: 🐛 should not display slash menu if has following chars

- packages/plugins/preset-commonmark/src/mark/strong.ts
✅ Closes: #1209
Fix google doc misbehavior where pasted content will be wrapped in`<b>` tags.
CI
> fix: 🐛 google doc paste

- packages/components/package.json
- packages/components/src/__internal__/components/icon.tsx
- packages/components/src/code-block/view/components/preview-panel.tsx
- packages/components/src/image-block/view/index.ts
- packages/components/src/image-inline/components/image-inline.tsx
- packages/components/src/image-inline/view.ts
- packages/components/src/link-tooltip/edit/edit-view.ts
- pnpm-lock.yaml
> feat: santinize url input

- e2e/tests/crepe/list.spec.ts
- packages/components/src/list-item-block/view.ts
✅ Closes: #1853
Fix the focus behavior of list item.
E2E
> fix: 🐛 list item component should be focused when created

- packages/crepe/src/theme/common/code-mirror.css
Add missing style for codemirror search panel.
Manually.
> fix: 🐛 missing style for codemirror search panel

- packages/crepe/package.json
- packages/kit/package.json
The postcss-cli cannot resolve input params around with single quotes on Windows OS.
```bash
C:\Users\86159\AppData\Local\pnpm\pnpm.cmd run build
> @milkdown/kit@7.11.1 build D:\person\milkdown\packages\kit
> postcss 'src' --base 'src' --dir 'lib'
Input Error: You must pass a valid list of files to parse
 ELIFECYCLE  Command failed with exit code 1.
Process finished with exit code 1
```
Also the single quotes is unnecessary on Linux OS.
Running `pnpm build` on my Windows machine and running `pnpm build` on GitHub Codespaces virtual Linux workspace.
> fix: fix running postcss-cli error with single quotes on Windows OS

- e2e/tests/crepe/list.spec.ts
- packages/components/src/list-item-block/view.ts
✅ Closes: #1917
Should focus the editor when clicking todo list.
E2E
> fix: 🐛 should focus editor when clicking todo list

- docs/api/crepe.md
- packages/crepe/src/feature/toolbar/config.ts
- packages/crepe/src/feature/toolbar/index.ts
Expose builder in toolbar config
CI
- `main` 
- \#1950 :point\_left:
> feat: 🎸 expose builder in toolbar config

- docs/api/crepe.md
- packages/crepe/src/feature/block-edit/index.ts
- packages/crepe/src/feature/block-edit/menu/config.ts
- packages/crepe/src/utils/index.ts
- packages/crepe/src/utils/types.ts
- storybook/stories/crepe/setup.ts
✅ Closes: #1916
Improve the block menu config api.
- Replaced flat configuration properties with nested group-based configuration
- Introduced three main configuration groups:
- `textGroup`: For text-related blocks (paragraphs, headings, quotes, dividers)
- `listGroup`: For list-related blocks (bullet, ordered, task lists)
- `advancedGroup`: For advanced blocks (images, code blocks, tables, math)
- Added `DeepPartial` utility type for better type inference
- Introduced nullable configuration options to allow disabling specific menu items
- Improved type definitions for menu item configurations
- Each menu item can now be individually enabled/disabled by setting it to `null`
- Groups can be completely hidden by setting the entire group to `null`
- Maintained backward compatibility with …
> feat: 🎸 improve the block menu config api

- packages/components/src/code-block/view/node-view.ts
Closes: #1963
Fix the issue that execute undo history(ctrl-z) in a code block will scroll to code block's top.
Manually
- `main` 
- \#1967 :point\_left:
> fix: 🐛 overflow codemirror scroll to top

- packages/plugins/plugin-emoji/package.json
- packages/plugins/plugin-emoji/src/emoji-render.spec.ts
- packages/plugins/plugin-emoji/src/index.ts
- packages/plugins/plugin-emoji/vitest.config.ts
- pnpm-lock.yaml
Editor crash if the provided emoji is not available in twemoji
✅ Closes: #1834
Unit Test
- `main` 
- \#1999 :point\_left:
> fix: 🐛 emoji crash if not available in twemoji

- e2e/tests/input/italic.spec.ts
- packages/plugins/preset-commonmark/src/mark/emphasis.ts
Fixes an issue where the emphasis input rule allows for matching to occur on intra-word underscores.
*Before*
```
the_lunatic_is_on_the_grass => Match
```
*After*
```
the_lunatic_is_on_the_grass => No match
```
See: https://spec.commonmark.org/0.31.2/#example-374
- Manual 
- Included e2e test
Before:
https://github.com/user-attachments/assets/c87c570c-10f4-46ed-b4f3-e679ebfd2d40
After:
https://github.com/user-attachments/assets/145e7a5d-7d7b-4e2c-9ef8-3d4215cc6792
> fix: emphasis matching on intra-word underscores

- e2e/package.json
- e2e/tests/input/strike-through.spec.ts
- package.json
- packages/plugins/preset-gfm/src/mark/strike-through.ts
Fixes an issue where the strikethrough input rule matches intra word, making it impossible to type file paths: 
```
C:/test/~apple~/
```
- e2e test
> fix: strikethrough matching on intra-word tilde

- e2e/package.json
- e2e/tests/input/bold.spec.ts
- packages/plugins/preset-commonmark/src/mark/strong.ts
- pnpm-lock.yaml
✅ Closes: #2032
Improve strong inputrule to match cases like: `a**"foo"**`
- `main` 
- \#2036 :point\_left:
> fix: 🐛 improve input rule of strong mark

- packages/components/src/image-block/view/index.ts
- packages/components/src/image-inline/view.ts
Should not load image before setup the proxy.
Manually.
- `main` 
- \#2110 :point\_left:
> fix: 🐛 image proxy time sequence
