Milkdown/milkdown

gh-pages/main.ts
packages/core/src/editor/index.ts
packages/core/src/editor/plugin.ts
packages/core/src/editor/view.ts
packages/plugin-prism/app/main.ts
packages/plugin-prism/src/index.ts

feat: plugin loader

---

packages/core/src/abstract/mark.ts
packages/core/src/abstract/node.ts
packages/core/src/editor/index.ts
packages/core/src/editor/view.ts
packages/core/src/utility/prosemirror.ts

#17 
@xiadd
View property added by this pr.

feat(core): add node and mark view

---

gh-pages/pages/guide/commands/index.zh-hans.md
gh-pages/pages/guide/getting-started/index.zh-hans.md
gh-pages/pages/guide/interacting-with-editor/index.zh-hans.md
gh-pages/pages/guide/keyboard-shortcuts/index.zh-hans.md
gh-pages/pages/guide/styling/index.zh-hans.md
gh-pages/pages/guide/why-milkdown/index.zh-hans.md
gh-pages/pages/integrations/react/index.zh-hans.md
gh-pages/pages/integrations/vue/index.zh-hans.md
gh-pages/pages/internals/internal-plugins/index.zh-hans.md
gh-pages/pages/internals/node-and-mark/index.zh-hans.md
gh-pages/pages/internals/parser/index.zh-hans.md
gh-pages/pages/internals/serializer/index.zh-hans.md
gh-pages/pages/plugins/example-custom-syntax/index.zh-hans.md
gh-pages/pages/plugins/using-plugins/index.zh-hans.md
gh-pages/pages/plugins/writing-plugins/index.zh-hans.md

- fix(docs): zh-hans punctuation issues
- fix(docs): zh-hans detail issues

fix(docs): zh-hans detail issues

---

gh-pages/pages/plugins/writing-syntax-plugins/index.md

This includes updates to account for newly reworked plugin system.  I'm sorry I can't also update the Chinese language version but as you can see it's not a code-only update, so I wouldn't be confident copying any of these changes over to that doc.
I've also forked the sandbox demo of this code so these changes can be copied into the current sandbox; https://codesandbox.io/s/milkdown-custom-syntax-forked-1dbzk

docs: ✏️ update english writing syntax plugin doc for version 5

---

gh-pages/component/MilkdownEditor/codeSandBox.ts
packages/plugin-cursor/src/index.ts
packages/preset-commonmark/src/node/hr.ts
packages/utils/src/composable/$command.ts
packages/utils/src/composable/$inputRule.ts
packages/utils/src/composable/$mark.ts
packages/utils/src/composable/$node.ts
packages/utils/src/composable/$prose.ts
packages/utils/src/composable/$remark.ts
packages/utils/src/composable/$shortcut.ts
packages/utils/src/composable/index.ts
packages/utils/src/index.ts
packages/utils/src/types.ts

Add composable plugin API for milkdown.
Before:
```typescript
import directive from "remark-directive";
const id = "iframe";
const iframe = createNode(() => ({
id,
schema: () => ({
attrs: {
src: { default: null }
},
group: "inline",
inline: true,
marks: "",
atom: true,
parseDOM: [
{
tag: "iframe",
getAttrs: (dom) => {
if (!(dom instanceof HTMLElement)) {
throw new Error();
}
return {
src: dom.getAttribute("src")
};
}
}
],
toDOM: (node) => ["iframe", { ...node.attrs, class: "iframe" }, 0],
parseMarkdown: {
match: (node) => {
return node.type === "textDirective" && node.name === "iframe";
},
runner: (state, node, type) => {
state.addNode(type, { src: (node.attributes as { src: string }).src });
}
},
toMarkdown: {
match: (node) => node.type.name === id,
runner: (state, node) => { …
```

Composable Plugins

---

gh-pages/pages/integrations/react/index.md
gh-pages/pages/integrations/react/index.zh-hans.md
gh-pages/pages/integrations/vue/index.md
gh-pages/pages/integrations/vue/index.zh-hans.md
packages/react/app/main.tsx
packages/react/src/Editor.tsx
packages/react/src/Portals.tsx
packages/react/src/ReactNode.tsx
packages/react/src/ReactNodeView.tsx
packages/vue/app/VueEditor.tsx
packages/vue/src/Editor.tsx
packages/vue/src/VueNode.tsx
packages/vue/src/VueNodeView.tsx

Add ctx as context for vue and react renderer.
✅ Closes: [232](https://github.com/Saul-Mirone/milkdown/issues/232)

feat: 🎸 add ctx for react and vue renderer

---

gh-pages/style.css
packages/plugin-menu/src/menubar.ts
packages/plugin-table/src/operator-plugin/calc-pos.ts
packages/plugin-tooltip/src/button-manager/calc-button-pos.ts
packages/plugin-tooltip/src/input-manager/calc-input-pos.ts
packages/prose/src/toolkit/position/index.ts
packages/theme-nord/src/override.ts

✅ Closes: [248](https://github.com/Saul-Mirone/milkdown/issues/248)

Optimize tooltip position

---

gh-pages/pages/guide/getting-started/index.md

Awesome project! I noticed some typos when reading the docs.

Fix some typos

---

packages/plugin-menu/README.md
packages/plugin-menu/src/default-config.ts

Runned prettier, GitHub CI.🤖🙏
I have added plain text option for the default menu config, also for README files. ✨
I implemented a dirty workaround for it, if you have a better idea please tell me. I'm happy to see a elegant solution for this so we can improve this lovely project together! 🥰

feat: added plain text option as default.

---

README.md
packages/design-system/src/keys.ts
packages/design-system/src/manager.ts
packages/plugin-diagram/README.md
packages/plugin-diagram/src/index.ts
packages/plugin-diagram/src/node.ts
packages/plugin-diagram/tsconfig.json
packages/plugin-diagram/typings/mermaid/index.d.ts
packages/plugin-diagram/typings/mermaid/mermaidAPI.d.ts
packages/plugin-menu/README.md
packages/plugin-menu/src/menubar.ts
packages/theme-nord/src/index.ts
packages/theme-nord/src/style.ts
packages/theme-pack-helper/src/renderer-preset/code-fence.ts
packages/theme-tokyo/src/index.ts
packages/theme-tokyo/src/style.ts

Note that this commit includes various fixes needed to be reviewed includes eslint-disable files. Please remind.
Edit: I will remove the type definition after merged mermaid type definition, and add themeVariable configuration after I finished that part of type definition.

feat: 🎸 provide mermaid theme options for diagram

---

gh-pages/component/MilkdownEditor/MilkdownEditor.tsx
packages/core/src/internal-plugin/editor-view.ts
packages/utils/src/index.ts
packages/utils/src/macro/index.ts
packages/utils/src/macro/insert.ts
packages/utils/src/macro/outline.ts
packages/utils/src/macro/replace-all.ts
packages/utils/src/macro/switch-theme.ts

feat: 🎸 add some macros

---

packages/plugin-tooltip/src/index.ts
packages/plugin-tooltip/src/item.ts

Note: no ci is runned, awaiting for triage and review

feat: customizable hover menu

---

README.md

I would also recommend to use https://github.com/antfu/sponsorkit to automate 😊 
Happy to sponsor you and thank you for your amazing work ❤️

docs: update sponsors

---

gh-pages/pages/plugins/plugin-factories/index.md
packages/utils/src/factory/create-mark.ts
packages/utils/src/factory/create-node.ts
packages/utils/src/factory/create-plugin.ts
packages/utils/src/types.ts

feat: 🎸 make factories can inject slices

---

.vscode/settings.json
examples/collaboration/index.html
examples/collaboration/main.ts
gh-pages/pages/guide/collaborative-editing/index.md
gh-pages/public/sitemap.xml
gh-pages/route/page-config.ts
gh-pages/route/page-dict.ts
packages/core/src/internal-plugin/editor-state.ts
packages/plugin-collaborative/README.md
packages/plugin-collaborative/src/collab-service.ts
packages/plugin-collaborative/src/index.ts
packages/preset-commonmark/src/mark/link.ts

feat: 🎸 improve the collab support

---

gh-pages/pages/integrations/solidjs/index.zh-hans.md

i18n: add zh-hans doc for solid js

---

gh-pages/pages/plugins/composable-plugins/index.md
packages/utils/package.json
packages/utils/src/composable/$command.ts
packages/utils/src/composable/$inputRule.ts
packages/utils/src/composable/$mark.ts
packages/utils/src/composable/$node.ts
packages/utils/src/composable/$prose.ts
packages/utils/src/composable/$remark.ts
packages/utils/src/composable/$shortcut.ts
packages/utils/src/composable/$view.ts
packages/utils/src/composable/utils.ts
packages/utils/src/types.ts
pnpm-lock.yaml

Add promise support for composable utils
Closes: #561

Promise composable

---

gh-pages/component/MilkdownEditor/editor.ts
gh-pages/package.json
gh-pages/pages/official-plugins/plugin-trailing/index.md
gh-pages/route/page-config.ts
gh-pages/route/page-dict.ts
packages/plugin-trailing/README.md
packages/plugin-trailing/package.json
packages/plugin-trailing/src/index.ts
packages/plugin-trailing/tsconfig.json
packages/plugin-trailing/vite.config.ts
pnpm-lock.yaml
vite.config.ts

This is a trailing plugin for milkdown.
An empty paragraph (or any node you want) will be append to the end of the documentation automatically.
Test manually and show it in online demo.
Special thanks to @4-1-1 for the effort he made in https://github.com/Saul-Mirone/milkdown/pull/537.

feat: 🎸 add trailing plugin

---

examples/react/component/milkdown/CodeFence/index.tsx
examples/react/main.tsx
examples/vue/CodeFence/CodeFence.vue
packages/react/src/Editor.tsx
packages/react/src/ReactNodeView.tsx
packages/vue/src/VueNode.tsx
packages/vue/src/VueNodeView.tsx

feat: 🎸 make node and decorations up to date in react and vue

---

packages/ctx/src/timing/timing.ts

fix: 🐛 memory leak of timing listener

---

packages/plugin-menu/src/index.ts
packages/plugin-menu/src/menubar.ts

fix: 🐛 scroll view when update plugin

---

website/pages/plugins/plugins-101/index.md
website/pages/plugins/plugins-101/index.zh-hans.md

Fix plugin 101 typo

---

packages/theme-nord/src/style.ts
packages/theme-tokyo/src/style.ts

https://github.com/Saul-Mirone/milkdown/blob/d99eef9cf0016a96feac880e1b70b1903907626b/packages/theme-nord/src/style.ts#L199-L206
204行引入了错误的变量`code`
https://github.com/Saul-Mirone/milkdown/blob/d99eef9cf0016a96feac880e1b70b1903907626b/packages/theme-nord/src/style.ts#L164-L168
改为
```
font-family: ${manager.get(ThemeFont, 'code')};
```

fix: 🐛 code-inline style

---

e2e/cypress/e2e/preset-commonmark/input.cy.ts
e2e/snapshots.js
packages/preset-commonmark/src/mark/em.ts
packages/preset-commonmark/src/mark/strong.ts

-   [ ] I read the contributing guide 
-   [ ] I agree to follow the code of conduct 
不支持一个字
https://user-images.githubusercontent.com/1715916/186644356-17c934b2-c7e6-4f9e-b83a-4331f1c65f25.mov

fix: 🐛 em strong not support 1 word inside

---

packages/preset-commonmark/src/mark/em.ts
packages/preset-commonmark/src/node/image.ts

fix: 🐛 em regex can match "__B_"

---

website/pages/integrations/react/index.zh-hans.md

-   [x] I agree to follow the code of conduct

docs: syntax error in react intergrations

---

website/pages/guide/faq/index.zh-hans.md
website/pages/guide/getting-started/index.zh-hans.md
website/pages/theme/theme-nord/index.zh-hans.md
website/pages/theme/theme-tokyo/index.zh-hans.md
website/route/page-dict.ts

-   [x] I agree to follow the code of conduct

docs: revise zh-docs

---

packages/plugin-emoji/src/remark-twemoji.ts

✅ Closes: #784
[#784 [Bug] plugin-emoji: unable to render multiple emoji](https://github.com/Saul-Mirone/milkdown/issues/784)
Before:
After:
Before:
After:

fix: 🐛 reset emoji regex lastIndex

---

packages/plugin-emoji/src/filter/helper.ts
packages/plugin-emoji/src/filter/index.ts
packages/plugin-emoji/src/node.ts
packages/plugin-emoji/src/parse.ts
packages/plugin-emoji/src/remark-twemoji.ts

Add Twemoji options (https://github.com/twitter/twemoji#object-as-parameter) to the `plugin-emoji`.
> Reason: I need to customize the Twemoji `base` url.
1. Run an example
```typescript
.use(
emoji.configure(emojiNode, {
twemojiOptions: {
base: 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/',
},
}),
)
```

feat: 🎸 add twemoji options to plugin-emoji

---

packages/plugin-slash/src/prose-plugin/dropdown.ts
packages/plugin-slash/src/prose-plugin/view.ts
packages/plugin-slash/src/style.ts

Slash Dropdown is not fully displayed, need to scroll editor scrollbar.
**Changes**: Slash Dropdown adaptive height, orientation.
1. Test cases:

feat: 🎸 optimize slash dropdown height and position

---

packages/plugin-emoji/src/filter/index.ts
packages/plugin-emoji/src/filter/style.ts

Emoji Filter is not fully displayed, need to scroll editor scrollbar.
**Changes**: Emoji Filter adaptive height, orientation.
1. Test cases:

feat: 🎸 optimize emoji filter height and position

---

packages/theme-pack-helper/src/renderer-preset/task-list-item.ts

Task list item checked color wrong.
1. Test cases:

fix: 🐛 task list item checked style

---

packages/preset-gfm/src/table/plugin/column-resizing.ts

✅ Closes: #806
-   [ ] I read the contributing guide 
-   [ ] I agree to follow the code of conduct 
#806 
1. Test cases:

fix: 🐛 table column resizing handle position

---

packages/design-system/src/keys/renderer/code-fence.ts
packages/preset-commonmark/src/node/code-fence.ts
packages/theme-pack-helper/src/renderer-preset/code-fence.ts

Code Fence Select is not fully displayed, need to scroll editor scrollbar.
**Changes**: Code Fence Select adaptive height, orientation.
1. Test cases:

feat: 🎸 optimize code fence select height and position

---

packages/plugin-block/src/block-menu-dom.ts

Block Menu is not fully displayed, need to scroll editor scrollbar.
**Changes**: Block Menu adaptive height, orientation.
1. Test cases:

feat: 🎸 optimize block menu height and position

---

e2e/package.json
e2e/src/main.ts
e2e/src/preset-commonmark.ts
e2e/src/preset-gfm.ts
packages/theme-nord/README.md
packages/theme-nord/package.json
packages/theme-nord/postcss.config.cjs
packages/theme-nord/src/index.ts
packages/theme-nord/src/style.css
packages/theme-nord/tailwind.config.cjs
packages/theme-nord/tsconfig.json
packages/theme-nord/vite.config.ts
pnpm-lock.yaml
website/package.json
website/src/component/DocRenderer/index.tsx
website/src/component/Home/Editor.tsx
website/src/component/Playground/EditorComponent/config.ts
website/src/component/Playground/EditorComponent/style.css
website/src/component/Playground/Milkdown/usePlayground.ts
website/src/main.tsx

This PR introduce the `@milkdown/theme-nord` back.

feat: 🎸 add nord theme back

---

packages/core/vite.config.ts
packages/ctx/vite.config.ts
packages/exception/vite.config.ts
packages/plugin-block/vite.config.ts
packages/plugin-clipboard/vite.config.ts
packages/plugin-collaborative/vite.config.ts
packages/plugin-cursor/vite.config.ts
packages/plugin-diagram/vite.config.ts
packages/plugin-emoji/vite.config.ts
packages/plugin-history/vite.config.ts
packages/plugin-indent/vite.config.ts
packages/plugin-listener/vite.config.ts
packages/plugin-math/vite.config.ts
packages/plugin-prism/vite.config.ts
packages/plugin-slash/vite.config.ts
packages/plugin-tooltip/vite.config.ts
packages/plugin-trailing/vite.config.ts
packages/plugin-upload/vite.config.ts
packages/preset-commonmark/vite.config.ts
packages/preset-gfm/vite.config.ts
packages/prose/vite.config.ts
packages/react/vite.config.ts
packages/theme-nord/vite.config.ts
packages/transformer/vite.config.ts
packages/utils/vite.config.ts
packages/vue/vite.config.ts
vite.config.ts

Upgrade the vite config for build.

chore: 🤖 upgrade vite build config

---

.changeset/curly-pants-sneeze.md
.changeset/funny-pugs-listen.md
.changeset/little-fans-think.md
.changeset/lucky-lamps-float.md
.changeset/nervous-seals-arrive.md
.changeset/pre.json
.changeset/slow-masks-suffer.md
packages/plugin-block/src/serialize-for-clipboard.ts
packages/plugin-collaborative/README.md
packages/plugin-collaborative/package.json
packages/plugin-collaborative/src/index.ts
packages/prose/package.json
packages/prose/src/changeset.ts
pnpm-lock.yaml
vite.config.ts

Upgrade prosemirror

---

e2e/cypress/e2e/preset-gfm/input.cy.ts
packages/preset-gfm/src/composed/inputrules.ts
packages/preset-gfm/src/node/task-list-item.ts

Closes: #905 
Add input rule for create task list.
E2E test.

feat: 🎸 add inputrule for task list

---

packages/preset-commonmark/src/plugin/sync-list-order-plugin.ts

Closes: #836 
Optimize the ordered list sync plugin to handle the dnd issue.
Tested manually.

fix: 🐛 ordered list won't sync when dragged into a new ol

---

e2e/cypress/e2e/plugin-listener/plugin.cy.ts
e2e/package.json
e2e/src/index.html
e2e/src/main.ts
e2e/src/plugin-listener.ts
e2e/src/style.css
packages/plugin-listener/package.json
packages/plugin-listener/src/index.ts
packages/preset-commonmark/src/plugin/inline-sync-plugin/inline-sync-plugin.ts
pnpm-lock.yaml

Inline sync plugin will cause dirty state in listener plugin and history plugin during the sync happens.
✅ Closes: #923
E2E

fix: 🐛 inline sync plugin causes unneed changes

---

e2e/cypress/e2e/plugin-clipboard/plugin.cy.ts
e2e/cypress/e2e/plugin-listener/plugin.cy.ts
e2e/cypress/support/commands.js
e2e/package.json
e2e/shim.d.ts
e2e/src/index.html
e2e/src/main.ts
e2e/src/plugin-clipboard.ts
e2e/src/style.css
pnpm-lock.yaml

Add e2e test for clipboard plugin.
E2E

test: 💍 add test case for clipboard

---

packages/ctx/src/context/slice.spec.ts
packages/ctx/src/context/slice.ts

✅ Closes: #920
Add a watcher to inspect value changes in slice.
Unit test

feat: add watcher for slice

---

.github/workflows/ci-for-pr.yml
.github/workflows/ci.yml
.gitignore
nx.json

chore: replace nx token

---

.github/workflows/ci-for-pr.yml
.github/workflows/ci.yml
.github/workflows/release-package.yml
.github/workflows/test.yml

-   [x] I agree to follow the code of conduct

ci: restore cache

---

e2e/cypress/e2e/preset-commonmark/input.cy.ts
packages/preset-commonmark/src/plugin/inline-sync-plugin/context.ts
packages/preset-commonmark/src/plugin/inline-sync-plugin/regexp.ts
packages/preset-commonmark/src/plugin/inline-sync-plugin/utils.ts

✅ Closes: #1044
Add support for escape * and _
E2E

feat: 🎸 add support for escape * and _

---

e2e/package.json
e2e/shim.d.ts
e2e/src/code-block/index.html
e2e/src/code-block/main.ts
e2e/src/code-block/style.css
e2e/src/index.html
e2e/src/utils.ts
e2e/vite.config.ts
package.json
packages/components/package.json
packages/components/rollup.config.js
packages/components/src/__internal__/icons.ts
packages/components/src/code-block/config.ts
packages/components/src/code-block/index.ts
packages/components/src/code-block/view/component.ts
packages/components/src/code-block/view/index.ts
packages/components/src/code-block/view/loader.ts
packages/components/src/code-block/view/node-view.ts
packages/components/src/code-block/view/style.ts
packages/components/src/code-block/view/utils.ts
packages/prose/package.json
pnpm-lock.yaml

Code mirror support for code block
https://github.com/Milkdown/milkdown/assets/10047788/928a70d2-bc75-42c5-94bc-f263f7677d07
E2E

feat: 🎸 add code block component

---

e2e/src/image-block/style.css
e2e/src/index.html
e2e/src/list-item-block/index.html
e2e/src/list-item-block/main.ts
e2e/src/list-item-block/style.css
e2e/vite.config.ts
packages/components/README.md
packages/components/package.json
packages/components/src/code-block/view/component.ts
packages/components/src/image-block/config.ts
packages/components/src/image-block/view/index.ts
packages/components/src/list-item-block/component.ts
packages/components/src/list-item-block/config.ts
packages/components/src/list-item-block/index.ts
packages/components/src/list-item-block/style.ts
packages/components/src/list-item-block/view.ts

Add list item block

---

packages/plugin-history/src/index.ts

-   [X] I read the contributing guide 
-   [X] I agree to follow the code of conduct 
typo

fix: typo of 'redo'

---

package.json
pnpm-lock.yaml

chore: 🤖 upgrade eslint config

---

e2e/src/data.ts
e2e/src/index.html
e2e/src/main.ts
e2e/src/style.css

chore: optimize e2e home page

---

package.json
pnpm-lock.yaml

chore: 🤖 upgrade ts to 5.3

---

e2e/src/data.ts
e2e/src/inline-image/index.html
e2e/src/inline-image/main.ts
e2e/src/inline-image/style.css
e2e/vite.config.mts
packages/components/package.json
packages/components/src/inline-image/component.ts
packages/components/src/inline-image/config.ts
packages/components/src/inline-image/index.ts
packages/components/src/inline-image/style.ts
packages/components/src/inline-image/view.ts
packages/components/src/link-tooltip/index.ts
packages/components/src/link-tooltip/slices.ts
packages/components/src/link-tooltip/tooltips.ts

Add inline image component.
CI

feat: 🎸 add inline image block

---

e2e/cypress/fixtures/blockquote.md
e2e/package.json
packages/components/package.json
pnpm-lock.yaml
tsconfig.base.json
tsconfig.json

chore: 🤖 bump deps

---

e2e/package.json
e2e/postcss.config.cjs
packages/components/package.json
packages/components/src/code-block/view/component.ts
packages/components/src/code-block/view/index.ts
packages/components/src/image-block/view/component.ts
packages/components/src/image-block/view/index.ts
packages/components/src/inline-image/component.ts
packages/components/src/inline-image/view.ts
packages/components/src/link-tooltip/edit/edit-component.ts
packages/components/src/link-tooltip/edit/edit-configure.ts
packages/components/src/link-tooltip/edit/edit-view.ts
packages/components/src/link-tooltip/preview/preview-component.ts
packages/components/src/link-tooltip/preview/preview-configure.ts
packages/components/src/link-tooltip/preview/preview-view.ts
packages/components/src/list-item-block/component.ts
packages/components/src/list-item-block/view.ts
pnpm-lock.yaml

chore: bump atomico version

---

e2e/cypress/e2e/plugin-listener/plugin.cy.ts
e2e/package.json
e2e/src/plugin-listener/main.ts
packages/plugin-listener/src/index.ts

✅ Closes: #1155
The default value of listener plugin should be equal to the default value of the editor
E2E

fix: 🐛 default value of listener plugin

---

packages/plugin-emoji/src/__internal__/parse.ts

fix: 🐛 twemoji options type

---

packages/plugin-diagram/package.json
pnpm-lock.yaml

fix #1267 .
further testing may needed.

fix(plugin-diagram): bump version of mermaid

---

e2e/package.json
packages/components/package.json
pnpm-lock.yaml

chore: fix lock file

---

packages/components/src/link-tooltip/preview/preview-configure.ts
packages/components/src/link-tooltip/utils.ts
packages/crepe/src/theme/classic-dark/style.css
packages/crepe/src/theme/classic/style.css

fix: 🐛 improve styles for crepe

---

packages/plugin-automd/src/config.ts

PR #1171 moved the location of the default config file. This PR adjusts sources to changes.

docs: update default config reference

---

e2e/src/components/code-block.css
e2e/src/components/code-block.stories.ts
e2e/src/components/image-block.css
e2e/src/components/image-block.stories.ts

Add components in storybook.
CI

feat: add components in storybook

---

e2e/src/components/list-item-block.css
e2e/src/components/list-item-block.stories.ts

Add list item block in stories
CI

test: add list item block in stories

---

packages/components/src/list-item-block/component.ts
packages/components/src/list-item-block/config.ts
packages/components/src/list-item-block/view.ts
packages/crepe/src/feature/list-item/index.ts

list item block should respect readonly mode
manually and ci

fix: list item block should respect readonly mode

---

e2e/public/typescript-label.svg
e2e/src/components/inline-image-block.css
e2e/src/components/inline-image-block.stories.ts

Add inline image block in storybook.

chore: add inline image block in storybook

---

e2e/src/components/link-tooltip.css
e2e/src/components/link-tooltip.stories.ts

Add link tooltip in storybook
CI and manully.

chore: add link tooltip in storybook

---

e2e/package.json
package.json

chore: 🤖 adjust script names

---

packages/plugin-block/package.json
packages/plugin-block/src/block-plugin.ts
packages/plugin-block/src/block-provider.ts
packages/plugin-block/src/block-service.ts
packages/preset-commonmark/src/node/list-item.ts
pnpm-lock.yaml

Optimize ux of block handle
Manually

feat: 🎸 optimize block handle

---

e2e/.storybook/preview.ts
e2e/stories/components/code-block.css
e2e/stories/components/code-block.stories.ts
e2e/stories/components/image-block.stories.ts
e2e/stories/components/inline-image-block.stories.ts
e2e/stories/components/link-tooltip.stories.ts
e2e/stories/components/list-item-block.stories.ts
e2e/stories/plugins/emoji.stories.ts
e2e/stories/plugins/listener.stories.ts
e2e/stories/presets/preset-commonmark/commands.stories.ts
e2e/stories/presets/preset-commonmark/input-rules.stories.ts
e2e/stories/presets/preset-commonmark/main.stories.ts
e2e/stories/presets/preset-commonmark/shortcut.stories.ts
e2e/stories/presets/preset-gfm/main.stories.ts

improve style org of storybook
ci

chore: 🤖 improve styles in story book

---

packages/plugins/preset-commonmark/src/node/list-item.ts

Closes: https://github.com/Milkdown/milkdown/issues/1353
CI

fix: ordered list paste becomes unordered list

---

packages/components/src/image-block/view/component.ts
packages/components/src/image-inline/component.ts
packages/crepe/src/theme/_internal/classic-common.css
packages/crepe/src/theme/common/image-block.css
packages/plugins/plugin-block/src/block-provider.ts
packages/plugins/plugin-slash/src/slash-provider.ts
packages/plugins/plugin-tooltip/src/tooltip-provider.ts

Add offset plugin for `floating-dom/dom`

feat: add offset for floating ui

---

packages/crepe/src/feature/block-edit/menu/component.ts
packages/crepe/src/theme/common/block-edit.css
packages/crepe/src/theme/common/cursor.css

Fix the double scroll behavior of slash menu

fix: slash menu scroll behavior

---

.github/workflows/release-package.yml
.github/workflows/start-agents.yml
.github/workflows/start-nx-cloud.yml
.github/workflows/stop-nx-cloud.yml
.github/workflows/test.yml
CONTRIBUTING.md
package.json

ci: use core pack

---

e2e/stories/components/table-block.css
packages/components/src/table-block/view/drag.ts
packages/components/src/table-block/view/pointer.ts
packages/components/src/table-block/view/utils.ts

Table drag and drop cannot work sometimes because of a chrome bug:
https://stackoverflow.com/questions/14203734/dragend-dragenter-and-dragleave-firing-off-immediately-when-i-drag

fix: table dnd cannot work sometimes

---

packages/crepe/src/feature/block-edit/menu/component.ts
packages/crepe/src/feature/block-edit/menu/index.ts
packages/crepe/src/feature/toolbar/index.ts
packages/plugins/plugin-tooltip/src/tooltip-provider.ts

fix: tooltip plugin offset

---

packages/components/src/code-block/view/component.ts
packages/crepe/src/theme/common/code-mirror.css

Add no result state for code mirror component search list

feat: add code mirror no result state

---

e2e/cypress/e2e/preset-commonmark/transform.cy.ts
e2e/cypress/fixtures/hardbreak.md
packages/plugins/preset-commonmark/src/node/hardbreak.ts
packages/plugins/theme-nord/src/style.css

✅ Closes: #1429
Fix the issue that inline hardbreak prevents navigation
E2E

fix: 🐛 inline hardbreak prevents navigation

---

e2e/stories/crepe/setup.ts
packages/crepe/src/core/crepe.ts
packages/crepe/src/feature/block-edit/handle/component.ts
packages/crepe/src/feature/block-edit/handle/index.ts
packages/crepe/src/feature/block-edit/index.ts
packages/crepe/src/feature/block-edit/menu/component.ts
packages/crepe/src/feature/block-edit/menu/config.ts
packages/crepe/src/feature/block-edit/menu/index.ts
packages/crepe/src/feature/code-mirror/index.ts
packages/crepe/src/feature/image-block/index.ts
packages/crepe/src/feature/index.ts
packages/crepe/src/feature/link-tooltip/index.ts
packages/crepe/src/feature/list-item/index.ts
packages/crepe/src/feature/shared.ts
packages/crepe/src/feature/table/index.ts
packages/crepe/src/feature/toolbar/component.ts
packages/crepe/src/feature/toolbar/index.ts

feat: make crepe icons configurable

---

CONTRIBUTING.md
e2e/package.json
package.json
pnpm-lock.yaml

Remove unused npm scripts and update contribution guide
CI

chore: cleanup

---

packages/crepe/src/feature/block-edit/handle/index.ts
packages/crepe/src/feature/block-edit/menu/config.ts
packages/crepe/src/feature/block-edit/menu/utils.ts

Fix a issue that the add button in crepe drag handle sometimes insert to wrong position

fix: block add position

---

.github/workflows/ci-for-pr.yml
.github/workflows/ci.yml
e2e/cypress.config.ts
e2e/entry.ts
e2e/package.json
e2e/src/crepe/main.ts
e2e/vite.config.mts
nx.json
packages/crepe/src/theme/common/block-edit.css
pnpm-lock.yaml

ci: use nx distribution

---

.changeset/grumpy-dodos-study.md

Prepare to release minor version.
CI

ci: trigger release

---

.changeset/wise-points-hope.md
packages/crepe/package.json
pnpm-lock.yaml

Crepe bundle and dependencies.

fix: crepe bundle

---

package.json
packages/components/package.json
pnpm-lock.yaml
vite.config.mts

Fix component lib dependencies
CI

fix: component dependencies

---

.changeset/green-spies-jam.md
packages/components/src/table-block/view/utils.ts
packages/crepe/src/feature/block-edit/handle/index.ts
packages/crepe/src/theme/common/block-edit.css
packages/plugins/plugin-block/src/__internal__/select-node-by-dom.ts
packages/plugins/plugin-block/src/block-provider.ts
storybook/stories/crepe/setup.ts

Fix block plugin display and internal errors.
CI and manually.

fix: 🐛 block plugin display and exception bugs

---

packages/plugins/plugin-tooltip/src/tooltip-provider.ts

fix(tooltop): shift tooltip when overflow on x-axis.

---

e2e/tests/input/heading.spec.ts
packages/plugins/preset-commonmark/src/plugin/sync-heading-id-plugin.ts

✅ Closes: #1567
Prevent duplicated ids for headings
CI

feat: 🎸 prevent duplicated ids for headings

---

packages/components/src/image-block/config.ts
packages/components/src/image-block/view/index.ts
packages/components/src/image-inline/config.ts
packages/components/src/image-inline/view.ts

Add url proxy for crepe.
Manually

feat: add image proxy for crepe

---

packages/crepe/src/feature/image-block/index.ts

Add image proxy config in crepe

fix: add image proxy config in crepe

---

.github/actions/setup/action.yml
.github/workflows/ci.yml
.github/workflows/fix.yml
.github/workflows/release.yml

ci: speed up

---

package.json

chore: remove husky install since it's deprecated

---

packages/crepe/src/feature/code-mirror/index.ts
pnpm-lock.yaml
storybook/package.json
storybook/stories/crepe/setup.ts
storybook/stories/crepe/style.css
storybook/stories/plugins/listener.css
storybook/stories/utils/shadow.ts
storybook/stories/utils/style.css

Add markdown inspector in storybook
manually

feat: add markdown inspector in storybook

---

e2e/shim.d.ts
e2e/src/crepe/main.ts
e2e/tests/crepe/listener.spec.ts
packages/crepe/src/core/crepe.ts
storybook/stories/crepe/setup.ts

✅ Closes: #1620
Add `on` api for crepe
Storybook and e2e

feat: 🎸 add `on` api for crepe

---

packages/integrations/react/package.json
packages/integrations/react/src/editor.tsx
packages/integrations/react/src/types.ts
packages/integrations/react/src/use-instance.ts
packages/integrations/vue/package.json
packages/integrations/vue/src/editor.tsx
packages/integrations/vue/src/types.ts
packages/integrations/vue/src/use-instance.ts
pnpm-lock.yaml
vite.config.mts

Use milkdown/kit in integrations
CI

chore: use kit in integrations

---

packages/plugins/theme-nord/vite.config.ts

✅ Closes: #1596
Fix generated css file name of theme nord.
Manually

fix: 🐛 theme nord css generated file

---

packages/crepe/src/feature/latex/block-latex.ts

✅ Closes: #1640
Fix remark transform error when no code block lang
CI

fix: 🐛 remark transform error when no code block lang

---

packages/components/src/table-block/view/drag.ts
packages/crepe/src/feature/block-edit/menu/config.ts

Fix errors when using table.
CI

fix: table errors

---

packages/components/src/image-block/view/component.ts
packages/components/src/image-inline/component.ts
packages/crepe/package.json
packages/plugins/plugin-diagram/package.json
packages/utils/package.json
pnpm-lock.yaml

chore: use short nanoid

---

packages/plugins/preset-commonmark/package.json
packages/plugins/preset-commonmark/src/node/heading.ts
pnpm-lock.yaml

Replace slugify with faster implementation.
Closes: #1601
CI

fix: remove slugify for performance consideration

---

packages/plugins/plugin-block/src/block-provider.ts
packages/plugins/plugin-slash/src/slash-provider.ts
packages/plugins/plugin-tooltip/src/tooltip-provider.ts

✅ Closes: #1635
Add root option for tooltip, slash and block plugin.
Manually

feat: 🎸 add root option for tooltip,slash,block

---

packages/components/src/image-block/view/component.ts
packages/components/src/image-inline/component.ts

Image upload button stop working when selected.
Manually

fix: image upload button stop working when selected

---

packages/plugins/preset-commonmark/src/node/list-item.ts

Should not allow blockquote in list.
Closes: #1714 
CI

fix: should not support blockquote in list

---

packages/plugins/plugin-block/src/block-plugin.ts
packages/plugins/plugin-block/src/block-provider.ts
packages/plugins/plugin-block/src/index.ts
packages/plugins/preset-commonmark/src/node/list-item.ts

Fix multi block handle instance.
Closes: #1725

fix: multi block handle

---

packages/plugins/preset-gfm/src/node/table/input.ts

1. Fix enter throws error in table
2. Table should have at least 2 rows
CI

fix: table enter and minimal rows

---

packages/components/src/table-block/view/view.ts

✅ Closes: #1751
Fix backward select text in table cell.
Manually

fix: 🐛 backward select text in table cell

---

packages/crepe/package.json
packages/crepe/src/feature/cursor/index.ts
packages/crepe/src/theme/common/cursor.css
pnpm-lock.yaml

Integrate [prosemirror-virtual-cursor](https://github.com/ocavue/prosemirror-virtual-cursor) to support bike-style cursor.
Thanks to @ocavue .
https://github.com/user-attachments/assets/be946741-5913-4dfc-b541-009d85ee7e2f
Manually.

feat: 🎸 add bike-style virtual cursor

---

packages/plugins/preset-commonmark/src/mark/inline-code.ts

Remove inline code mark inclusive config since we're using virtual cursor now.
CI

fix: remove inline code mark inclusive config

---

packages/components/package.json
packages/core/package.json
packages/crepe/package.json
packages/ctx/package.json
packages/exception/package.json
packages/integrations/react/package.json
packages/integrations/vue/package.json
packages/kit/package.json
packages/plugins/plugin-automd/package.json
packages/plugins/plugin-block/package.json
packages/plugins/plugin-clipboard/package.json
packages/plugins/plugin-collab/package.json
packages/plugins/plugin-cursor/package.json
packages/plugins/plugin-emoji/package.json
packages/plugins/plugin-history/package.json
packages/plugins/plugin-indent/package.json
packages/plugins/plugin-listener/package.json
packages/plugins/plugin-prism/package.json
packages/plugins/plugin-slash/package.json
packages/plugins/plugin-tooltip/package.json
packages/plugins/plugin-trailing/package.json
packages/plugins/plugin-upload/package.json
packages/plugins/preset-commonmark/package.json
packages/plugins/preset-gfm/package.json
packages/plugins/theme-nord/package.json
packages/prose/package.json
packages/transformer/package.json
packages/utils/package.json
pnpm-lock.yaml

Remove package level dev pack.
CI

chore: 🤖 remove packges level dev pack

---

.github/workflows/fix.yml

Add codegen script in fix ci
ci

ci: 🎡 add codegen in fix ci

---

packages/components/src/image-block/schema.ts
packages/plugins/preset-commonmark/src/mark/emphasis.ts
packages/plugins/preset-commonmark/src/mark/link.ts
packages/plugins/preset-commonmark/src/mark/strong.ts
packages/plugins/preset-commonmark/src/node/bullet-list.ts
packages/plugins/preset-commonmark/src/node/code-block.ts
packages/plugins/preset-commonmark/src/node/hardbreak.ts
packages/plugins/preset-commonmark/src/node/heading.ts
packages/plugins/preset-commonmark/src/node/html.ts
packages/plugins/preset-commonmark/src/node/image.ts
packages/plugins/preset-commonmark/src/node/list-item.ts
packages/plugins/preset-commonmark/src/node/ordered-list.ts
packages/plugins/preset-gfm/src/node/footnote/definition.ts
packages/plugins/preset-gfm/src/node/footnote/reference.ts
packages/plugins/preset-gfm/src/node/task-list-item.ts

Regarding https://discuss.prosemirror.net/t/heads-up-xss-risk-in-domserializer/6572.
CI

feat: 🎸 add validate props for schema

---

packages/crepe/src/core/crepe.ts

fix: crepe vue unmount error

---

packages/components/src/table-block/view/view.ts

Fix table component cleanup logic.
CI

fix: missing table component cleanup

---

e2e/package.json
e2e/src/index.html
e2e/src/main.ts
e2e/tsconfig.json
e2e/vite.config.mts
packages/crepe/src/feature/block-edit/menu/component.tsx
pnpm-lock.yaml

Migrate e2e playground to vue
CI

chore: 🤖 migrate playground to vue

---

README.md

Update jetbrains brand links in readme

docs: update jetbrains brand links in readme

---

e2e/shim.d.ts
e2e/src/utils.ts
e2e/tests/command/chain.spec.ts
e2e/tsconfig.json
packages/core/src/internal-plugin/commands.ts

Add command inline and chain.
```ts
const command = editor.get(commandCtx);
// command `command1`, `command2` and `inlineCommand` will be called in order until one of them return `true`
// calls [chainCommands](https://prosemirror.net/docs/ref/#commands.chainCommands) under the hood
command
.chain()
.pipe(command1Key)
.pipe(command2Key, payload)
.inline(inlineCommand)
.run();
// call an inline command directly.
command.inline(inlineCommand);
```
E2E.

feat: 🎸 add command inline and chain

---

packages/core/src/internal-plugin/commands.ts

Add missing command chain tsdoc.
Manually.

fix: missing command chain tsdoc

---

packages/crepe/src/theme/common/block-edit.css

Fix crepe slash menu icon style.
Closes: #1861 
Manually.

fix: 🐛 slash menu icon style

---

.changeset/mean-states-own.md
packages/crepe/src/theme/common/block-edit.css
packages/crepe/src/theme/common/toolbar.css

Closes: #1791
Fix crepe slash menu and toolbar z-index.
Manually.

fix: 🐛 crepe slash menu and toolbar z-index

---

.github/workflows/ci.yml
packages/plugins/theme-nord/src/index.ts
packages/plugins/theme-nord/src/style.css
packages/prose/package.json

✅ Closes: #1868
Fix nord theme in nuxt.
Maunally.

fix: 🐛 nord theme in nuxt

---

packages/crepe/src/theme/common/toolbar.css

✅ Closes: #1870
Should hide toolbar when link tooltip is shown
Manually

fix: 🐛 should hide toolbar when link tooltip is shown

---

e2e/shim.d.ts
e2e/src/crepe/main.ts
e2e/tests/crepe/code.spec.ts
packages/components/src/code-block/view/components/code-block.tsx
packages/components/src/code-block/view/components/language-picker.tsx
packages/components/src/code-block/view/node-view.ts
packages/components/src/image-block/view/index.ts
packages/components/src/image-inline/view.ts
packages/components/src/list-item-block/view.ts
packages/crepe/src/core/crepe.ts

✅ Closes: #1876
Fix the readonly mode for code block component.
E2E

fix: 🐛 readonly mode for code block component

---

e2e/src/plugin-listener/main.ts
e2e/tests/plugin/listener.spec.ts
packages/plugins/plugin-listener/src/index.ts

Add selection change event in listener plugin.
E2E

feat: add selection change event in listern plugin

---

packages/crepe/src/feature/block-edit/menu/config.ts

✅ Closes: #1903
Fix the `slashMenuTextLabel` config attribute.
Manually

fix: 🐛 slashMenuTextLabel config attribute

---

docs/api/crepe.md
packages/crepe/src/core/crepe.ts
packages/crepe/src/core/slice.ts
packages/crepe/src/feature/index.ts

Add documentation for crepe API reference.
CI

docs: ✏️ add api reference for crepe editor

---

docs/api/crepe.md
packages/components/src/code-block/config.ts
packages/components/src/code-block/view/components/language-picker.tsx
packages/components/src/code-block/view/components/preview-panel.tsx
packages/components/src/image-block/config.ts
packages/components/src/image-block/view/components/image-block.tsx
packages/components/src/image-block/view/components/image-input.tsx
packages/components/src/image-block/view/components/image-viewer.tsx
packages/components/src/image-inline/components/image-inline.tsx
packages/components/src/image-inline/config.ts
packages/components/src/link-tooltip/edit/component.tsx
packages/components/src/link-tooltip/preview/component.tsx
packages/components/src/link-tooltip/slices.ts
packages/crepe/src/feature/block-edit/handle/component.tsx
packages/crepe/src/feature/block-edit/handle/index.ts
packages/crepe/src/feature/block-edit/index.ts
packages/crepe/src/feature/block-edit/menu/config.ts
packages/crepe/src/feature/code-mirror/index.ts
packages/crepe/src/feature/image-block/index.ts
packages/crepe/src/feature/latex/index.ts
packages/crepe/src/feature/latex/inline-tooltip/component.tsx
packages/crepe/src/feature/link-tooltip/index.ts
packages/crepe/src/feature/list-item/index.ts
packages/crepe/src/feature/shared.ts
packages/crepe/src/feature/table/index.ts
packages/crepe/src/feature/toolbar/component.tsx
packages/crepe/src/feature/toolbar/index.ts
storybook/stories/crepe/setup.ts

Use string instead of function for icons.

refactor: 💡 use string instead of function for icons

---

packages/integrations/react/src/types.ts
packages/integrations/vue/src/use-get-editor.ts

Support crepe builder in react and vue.
CI

feat: 🎸 support crepe builder in react and vue

---

packages/integrations/vue/src/__tests__/crepe-builder.test.tsx
packages/integrations/vue/src/__tests__/crepe.test.tsx
packages/integrations/vue/src/__tests__/milkdown.test.tsx

Fix vue test warning
CI
- `main` 
- \#1979 :point\_left:

fix: 🐛 vue test warning

---

packages/core/src/internal-plugin/commands.ts
packages/core/src/internal-plugin/keymap.ts
packages/plugins/preset-commonmark/src/node/list-item.ts
packages/plugins/preset-gfm/src/node/table/input.ts
packages/utils/src/composable/composed/$use-keymap.ts

✅ Closes: #1534
Fix table shortcut priority.
Manually.
- `main` 
- \#1998 :point\_left:

fix: 🐛 table shortcut priority

---

packages/plugins/preset-gfm/src/node/task-list-item.ts
packages/utils/src/composable/composed/$mark-schema.ts
packages/utils/src/composable/composed/$node-schema.spec.ts
packages/utils/src/composable/composed/$node-schema.ts
packages/utils/vitest.config.ts

✅ Closes: #1764
Support extend a extended schema
Unit Test
- `main` 
- \#2001 :point\_left:

feat: 🎸 support extend a extended schema

---

docs/api/component-code-block.md
docs/api/component-image-block.md
docs/api/component-image-inline.md
docs/api/component-link-tooltip.md
docs/api/component-list-item-block.md
docs/api/component-table-block.md

✅ Closes: #2002
Update documentations for components.
- `main` 
- \#2003 :point\_left:

docs: ✏️ update documentations for components

---

e2e/tests/crepe/table.pom.ts
e2e/tests/crepe/table.spec.ts

Add e2e for table component.
Closes: #2024
e2e

test: 💍 add e2e for table

---

packages/transformer/src/parser/state.ts
packages/transformer/src/serializer/state.spec.ts

Add test case for trim spaces.
Unit Test
- `main` 
- \#2035 :point\_left:

test: 💍 add test case for trim spaces

---

packages/plugins/preset-commonmark/src/__test__/html.spec.ts
packages/plugins/preset-commonmark/src/plugin/remark-html-transformer.ts
packages/plugins/preset-commonmark/vitest.config.ts

Fix html in blockquote error.
Closes: #2039
Unit Test
- `main` 
- \#2041 :point\_left:

fix: 🐛 html in blockquote error

---

packages/components/src/list-item-block/component.tsx
packages/components/src/list-item-block/view.ts
packages/plugins/preset-commonmark/src/plugin/sync-list-order-plugin.ts

✅ Closes: #2028
Fix list component mount logic in safari.
Manually
- `main` 
- \#2042 :point\_left:

fix: 🐛 list component mount logic on safari

---

packages/components/src/list-item-block/view.ts

Fix doc mismatch when mounting doc with list item and list component.
✅ Closes: #2047
Manually
- `main` 
- \#2048 :point\_left:

fix: 🐛 doc mismatch when mounting doc with list item

---

dev/src/vite.ts
docs/api/plugin-highlight.md
packages/plugins/plugin-highlight/README.md
packages/plugins/plugin-highlight/package.json
packages/plugins/plugin-highlight/src/__test__/highlight.spec.ts
packages/plugins/plugin-highlight/src/__test__/vitest.setup.ts
packages/plugins/plugin-highlight/src/index.ts
packages/plugins/plugin-highlight/src/lowlight.ts
packages/plugins/plugin-highlight/src/refractor.ts
packages/plugins/plugin-highlight/src/shiki.ts
packages/plugins/plugin-highlight/src/sugar-high.ts
packages/plugins/plugin-highlight/tsconfig.json
packages/plugins/plugin-highlight/vite.config.ts
packages/plugins/plugin-highlight/vitest.config.ts
pnpm-lock.yaml
tsconfig.json

Add a new plugin: `@milkdown/plugin-highlight` to support  more code highlighter libraries.
Unit Test
- `main` 
- \#2067 :point\_left:

feat: add new highlight plugin

---

packages/transformer/src/parser/stack-element.spec.ts
packages/transformer/src/parser/state.spec.ts
packages/transformer/src/serializer/state.spec.ts
packages/transformer/tsconfig.json

Improve unit test of transformer
Unit Test
- `main` 
- \#2109 :point\_left:

test: 💍 improve unit test of transformer
